FROM {BASE_IMAGE}

USER root

COPY ./scripts /scripts
COPY {PROJECT_DIR} /project/{PROJECT_DIR}
RUN chown -R user: /project/{PROJECT_DIR}

USER user
WORKDIR /project/{PROJECT_DIR}

RUN /scripts/prepareproject.sh

EXPOSE {PORT}
ENV PYTHONPATH=/project/the_venv/lib/python{PYTHON_VERSION}/site-packages

CMD ["/bin/bash", "-c", ". /home/user/.local/bin/env && . /home/user/the_venv/bin/activate && uv run {ENTRYPOINT}"]
