apiVersion: permission.arangodb.com/v1alpha1
kind: ArangoPermissionToken
metadata:
  name: {{ template "template.releaseName" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "template.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  deployment:
    name: {{ .Values.arangodb_platform.deployment.name }}
  ttl: {{ .Values.auth.service_token.ttl | default "1h" | quote }}
  {{- if .Values.auth.service_token.roles }}
  roles:
    {{- range .Values.auth.service_token.roles }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  policy:
    statements:
      {{- range .Values.auth.service_token.policy_statements }}
      - actions:
          {{- range .actions }}
          - {{ . | quote }}
          {{- end }}
        resources:
          {{- range .resources }}
          - {{ . | quote }}
          {{- end }}
        effect: {{ .effect | quote }}
      {{- end }}
