FROM ubuntu:24.04

COPY ./scripts /scripts
RUN /scripts/debinstall.sh

WORKDIR /home/user
USER user

RUN /scripts/prepareuv.sh 3.13 python-arango phenolrs \
    torch torch-geometric torchaudio torchvideo

CMD [ "/scripts/entrypoint.sh" ]
