FROM ubuntu:24.04

COPY ./scripts /scripts
RUN /scripts/debinstall.sh

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-venv python3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home/user
USER user

RUN /scripts/prepareuv.sh python-arango phenolrs networkx 'urllib3>=2.2.0,<3'

CMD [ "/scripts/entrypoint.sh" ]
