---
# Image
images:
  application:
    registry: PLACEHOLDER
    image: arango-cypher2aql/service
    tag: PLACEHOLDER
    kind: Application
imagePullSecrets: []

# Deployment
arangodb_platform:
  deployment:
    name: deployment

# Profiles
profiles: ""

auth:
  service_token:
    ttl: "1h"
    roles:
      - "{SERVICE_NAME}-service"
    policy_statements:
      - actions:
          - "db:*"
        resources:
          - "db:database:*"
        effect: "Allow"